# Thông tin sinh viên

Họ và tên: Nguyễn Nguyên Khôi

MSSV: 21521009

Lớp: CS116.N21.KHCL

Bài tập 5

Ngày: 7-4-2023

# Bước 1: Load dữ liệu từ file CSV

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from google.colab import drive

In [2]:
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [3]:
dataset = pd.read_csv("gdrive/My Drive/50_Startups.csv")
dataset.head(7)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51

In [4]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X.shape)
print(y.shape)

(50, 4)
(50,)


In [5]:
y = y.reshape(len(y), 1)

# Bước 3: Chuyển đổi các đặc trưng dạng phân loại sang dạng số sử dụng OneHotEncoder

In [6]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

# Bước 2: Chia tập dữ liệu thành 2 phần train và test theo tỉ lệ 8:2

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Bước 4: Tạo mô hình Linear Regression với sklearn và huấn luyện trên dữ liệu train

In [8]:
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

LinearRegression()

# Bước 5: Sử dụng mô hình đã huấn luyện để dự đoán trên tập test

In [9]:
y_test_pred = lr_model.predict(X_test)

In [10]:
# r2_score on test set
print("R2 score on test set:", r2_score(y_test_pred, y_test))

R2 score on test set: 0.9293749209318531


In [11]:
# mean squared error on test set
test_mse = mean_squared_error(y_test_pred, y_test)
print("Mean squared error on test set:", test_mse)

Mean squared error on test set: 83502864.03256194


# Bước 6: Đánh giá hiệu quả của mô hình trên cả 2 tập train và test

In [12]:
y_train_pred = lr_model.predict(X_train)

In [13]:
# r2_score on test set
print("R2 score on test set:", r2_score(y_train_pred, y_train))

R2 score on test set: 0.9475731045123561


In [14]:
# mean squared error on test set
train_mse = mean_squared_error(y_train_pred, y_train)
print("Mean squared error on test set:", train_mse)

Mean squared error on test set: 81571001.80077367
